### PR TITLE
Fix osfamily issues, update JDK8 to latest

### PR DESCRIPTION
**Pull request by mojibake-umd**

### CODE REVIEW

**Comment by schrepfler** [comment]
Thanks!

**Comment by schrepfler** [comment]
Merged to master however the trevis job seems to be failing, we'll need to understand why, this used to pass so something is off.

**Comment by schrepfler** [comment]
Ok, a missing pair of curlies, updated the test to reflect the latest jdk update and it seems we're good on Travis. Now I just need to remember how on earth to publish this (or better, if I can automate it).

**Comment by mojibake-umd** [comment]
Thank you for adding me to the Repo. 
I have found https://forge.puppetlabs.com/aco/oracle_java which looks to be a module that is well maintained. But your module served me well, and I was able to contribute back. Thank you.

**Comment by schrepfler** [comment]
No worries, I need to get some automation in place so it auto-updates itself :)

**Pull request merged**
